import type { FishingTypeId } from '@/lib/fishing'

/**
 * Canonical product shape used across the UI and API responses. It intentionally
 * omits DB-only bookkeeping (createdAt/updatedAt) so the same type describes both
 * static catalog entries and rows fetched from Postgres.
 */
export interface Product {
  id: string
  aliexpressId: string
  title: string
  description: string
  imageUrl: string
  /** Gallery images (the first mirrors imageUrl). */
  images: string[]
  /** Alt text per gallery image (index-aligned with images; empty = fall back to title). */
  imageAlts: string[]
  /** Optional product video (mp4/hls url). */
  videoUrl: string
  price: number
  currency: string
  affiliateUrl: string
  category: string
  typeFishing: FishingTypeId | string
  /** Subcategory id within the main category (see SUBCATEGORIES); '' if unset. */
  subcategory: string
  rating: number
  reviews: number
  inStock: boolean
  /** SEO meta title (falls back to title). */
  seoTitle: string
  /** SEO meta description generated by the AI agent (falls back to description). */
  seoDescription: string
  /** Whether the copy was rewritten for SEO by the agent (not AliExpress text). */
  aiOptimized: boolean
}

export interface Guide {
  id: string
  title: string
  excerpt: string
  /** Article body in the lightweight markdown used across the app. */
  content: string
  coverImage: string
  /** Alt text for the cover image (SEO/accessibility). */
  coverImageAlt: string
  /** Related fishing category id, or '' for general guides. */
  typeFishing: string
  seoTitle: string
  seoDescription: string
  aiOptimized: boolean
  published: boolean
  createdAt: string
  updatedAt: string
}

export interface ChatMessage {
  role: 'user' | 'assistant' | 'system'
  content: string
}

export interface ChatProductRef {
  id: string
  title: string
  price: number
  currency: string
  imageUrl: string
}

export interface ChatApiResponse {
  success: boolean
  response?: string
  products?: ChatProductRef[]
  error?: string
}

export interface ProductsApiResponse {
  success: boolean
  products?: Product[]
  source?: 'catalog' | 'aliexpress' | 'database'
  error?: string
}

export interface ProductApiResponse {
  success: boolean
  product?: Product
  error?: string
}
