/**
 * Sea-fishing species: scoring profiles (how each species feeds — used by the
 * hourly forecast) plus rich fact-sheet data for the /especies pages and the
 * "Qué buscar hoy" recommender. All angling guidance is orientative; legal
 * minimum sizes vary by regulation and must be checked at the official source.
 */
export interface SpeciesProfile {
  id: string
  name: string
  emoji: string
  /**
   * Artículo determinado del nombre, para poder redactar "pesca DEL mero" y
   * "pesca DE LA lubina" sin equivocar el género ni el número.
   *
   * Se DECLARA en vez de deducirse de la terminación: en castellano la
   * terminación miente a menudo (el pargo / la brótola / el pez ballesta) y
   * además hay dos nombres en plural (las potas, los calamares). Deducirlo
   * daría "pesca de la mero" en la mitad del catálogo, que es justo el fallo
   * que este campo existe para impedir.
   */
  article: 'el' | 'la' | 'los' | 'las'
  /** Fotos reales en public/imagenesPeces — la primera es la de portada. */
  images: string[]
  /**
   * Rasgos VISUALES para identificar la especie en una foto, redactados
   * insistiendo en lo que la separa de sus parecidas.
   *
   * Existe porque medido con fotos degradadas (recortadas, oscuras, borrosas,
   * con flash) el detector acertaba solo el 69%, y TODOS los fallos eran
   * confusiones dentro de la misma familia: breca→dorada, dentón→dorada,
   * herrera→sargo, corvina→lubina. Dándole solo la lista de nombres, el modelo
   * sabe que es un espárido pero no cuál. Con la marca de campo sí.
   *
   * Son rasgos de guía de campo, estables y comprobables — no dependen de
   * temporada ni de normativa.
   */
  idTraits: string
  tagline: string
  // -- hourly scoring (activity) --
  solunar: number
  dawnDusk: number
  night: number
  windSweet: [number, number]
  windBonus: number
  windStrongAt: number
  wavePref: 'rough' | 'moderate' | 'calm'
  pressureFall: number
  // -- fact sheet / recommender --
  bestMonths: number[] // 1..12
  seaTempC: [number, number] // comfortable feeding range
  habitat: string
  depth: string
  hours: string
  technique: string
  baits: string
  /** Orientative reference size — the legal one is set by regulation. */
  minSizeNote: string
  gearCats: string[]
}

export const GENERAL: SpeciesProfile = {
  id: 'general',
  name: 'General',
  article: 'la',
  emoji: '🎣',
  images: [],
  // El perfil "general" no es una especie: no hay nada que identificar.
  idTraits: '—',
  tagline: 'Puntuación general para cualquier especie',
  solunar: 30,
  dawnDusk: 18,
  night: 4,
  windSweet: [8, 25],
  windBonus: 14,
  windStrongAt: 45,
  wavePref: 'moderate',
  pressureFall: 14,
  bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  seaTempC: [10, 28],
  habitat: '—',
  depth: '—',
  hours: '—',
  technique: '—',
  baits: '—',
  minSizeNote: '—',
  gearCats: ['canas', 'carretes'],
}

export const SEA_SPECIES: SpeciesProfile[] = [
  {
    id: 'lubina',
    name: 'Lubina',
    article: 'la',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_lubina.jpg'],
    idTraits: 'Cuerpo alargado y plateado con DOS aletas dorsales bien SEPARADAS. Vientre blanco, dorso gris azulado. Mancha oscura difusa en el borde del opérculo. Boca grande. Se confunde con la corvina: la lubina es más esbelta, más plateada y de escama más fina.',
    tagline: 'Rompiente, viento y poca luz',
    solunar: 26, dawnDusk: 22, night: 16, windSweet: [10, 35], windBonus: 16, windStrongAt: 55, wavePref: 'rough', pressureFall: 16,
    bestMonths: [9, 10, 11, 12, 1, 2, 3],
    seaTempC: [11, 20],
    habitat: 'Rompientes, espigones, desembocaduras y playas batidas',
    depth: '0–10 m, muy pegada a la orilla con mar movida',
    hours: 'Amanecer, atardecer y noche; con temporal, también de día',
    technique: 'Spinning con paseantes y jerkbaits; surfcasting nocturno',
    baits: 'Gusana, cangrejo y lanzón; señuelos de 9–14 cm',
    minSizeNote: '≈36 cm (orientativa; confirma la normativa vigente)',
    gearCats: ['senuelos', 'canas', 'carretes'],
  },
  {
    id: 'dorada',
    name: 'Dorada',
    article: 'la',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_dorada.jpg'],
    idTraits: 'Espárido de cuerpo ovalado y alto, plateado. Marca decisiva: BANDA DORADA transversal entre los ojos, y mancha oscura en el arranque de la línea lateral, sobre el opérculo. Perfil de la cabeza muy abrupto. Sin barras verticales en los flancos.',
    tagline: 'Aguas templadas y calmadas',
    solunar: 28, dawnDusk: 20, night: 8, windSweet: [5, 18], windBonus: 14, windStrongAt: 35, wavePref: 'calm', pressureFall: 12,
    bestMonths: [5, 6, 7, 8, 9, 10],
    seaTempC: [16, 26],
    habitat: 'Arenales, esteros y bajos rocosos con arena',
    depth: '2–15 m; entra a comer a la orilla con la subiente',
    hours: 'Primeras horas del día y cambio de marea',
    technique: 'Surfcasting a fondo con bajos finos; currican ligero',
    baits: 'Gusana americana, cangrejo ermitaño, mejillón, tita',
    minSizeNote: '≈20 cm (orientativa; confirma la normativa vigente)',
    gearCats: ['anzuelos', 'canas', 'plomos'],
  },
  {
    id: 'sargo',
    name: 'Sargo',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_sargo.jpg'],
    idTraits: 'Espárido plateado con BARRAS VERTICALES OSCURAS ANCHAS y bien marcadas en los flancos (unas 7-9), más gruesas y espaciadas que las de la herrera. Mancha negra en el pedúnculo caudal. Sin banda dorada entre los ojos.',
    tagline: 'Roca con algo de marejada',
    solunar: 26, dawnDusk: 18, night: 6, windSweet: [8, 22], windBonus: 14, windStrongAt: 40, wavePref: 'moderate', pressureFall: 12,
    bestMonths: [10, 11, 12, 1, 2, 3],
    seaTempC: [12, 19],
    habitat: 'Roca batida, espigones y bocanas de puerto',
    depth: '1–8 m, en la espuma de la rompiente',
    hours: 'De día con mar movida; mejor con marea subiendo',
    technique: 'Corcheo/flotador y pesca a fondo ligera entre rocas',
    baits: 'Camarón, mejillón, erizo, gusana de roca',
    minSizeNote: '≈15 cm (orientativa; confirma la normativa vigente)',
    gearCats: ['anzuelos', 'lineas', 'canas'],
  },
  {
    id: 'corvina',
    name: 'Corvina',
    article: 'la',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_corvina.jpg'],
    idTraits: 'Cuerpo alargado bronceado-plateado, más robusto que la lubina y de ESCAMA GRANDE y visible. Línea lateral marcada con poros. Boca grande, aleta caudal casi recta. UNA sola dorsal continua con escotadura, no dos separadas como la lubina.',
    tagline: 'Noche y agua removida',
    solunar: 26, dawnDusk: 20, night: 22, windSweet: [8, 28], windBonus: 14, windStrongAt: 48, wavePref: 'rough', pressureFall: 14,
    bestMonths: [5, 6, 7, 8, 9],
    seaTempC: [18, 26],
    habitat: 'Desembocaduras, esteros y playas profundas',
    depth: '2–12 m, cazando en agua turbia',
    hours: 'Noche cerrada, especialmente sin luna',
    technique: 'Surfcasting nocturno; spinning con vinilos grandes',
    baits: 'Sardina, cangrejo, vinilos XL y paseantes lentos',
    minSizeNote: '≈45 cm (orientativa; confirma la normativa vigente)',
    gearCats: ['canas', 'senuelos', 'plomos'],
  },
  {
    id: 'denton',
    name: 'Dentón',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_denton.jpg'],
    idTraits: 'Espárido azulado-plateado, grande, con DIENTES CANINOS PROMINENTES y visibles en la boca. Perfil de la frente muy abrupto en adultos; los jóvenes llevan puntos oscuros dispersos. NO tiene banda dorada entre los ojos (eso es la dorada).',
    tagline: 'Agua clara y corriente, a barco',
    solunar: 30, dawnDusk: 22, night: 2, windSweet: [5, 20], windBonus: 12, windStrongAt: 35, wavePref: 'calm', pressureFall: 12,
    bestMonths: [4, 5, 6, 9, 10, 11],
    seaTempC: [15, 24],
    habitat: 'Bajos rocosos, caídas y veriles desde embarcación',
    depth: '10–50 m sobre piedra',
    hours: 'Amanecer y horas de corriente',
    technique: 'Curricán con vivo, jigging medio-pesado',
    baits: 'Calamar y caballa viva; jigs de 100–200 g',
    minSizeNote: '≈35 cm (orientativa; confirma la normativa vigente)',
    gearCats: ['senuelos', 'carretes', 'lineas'],
  },
  {
    id: 'atun',
    name: 'Atún',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_atun.jpg'],
    idTraits: 'Túnido fusiforme y macizo, dorso azul oscuro metálico y vientre plateado, con pínulas amarillas en el pedúnculo caudal. Cuerpo muy grueso y aleta caudal en media luna rígida. Mucho más corpulento que el bonito.',
    tagline: 'El gigante: corrientes, comidas y barco',
    solunar: 22, dawnDusk: 20, night: 0, windSweet: [8, 25], windBonus: 12, windStrongAt: 40, wavePref: 'moderate', pressureFall: 10,
    bestMonths: [5, 6, 7, 8, 9, 10],
    seaTempC: [18, 28],
    habitat: 'Aguas abiertas, líneas de corriente y zonas de cebo',
    depth: '0–60 m, cazando en superficie o a media agua',
    hours: 'Pleno día; comidas explosivas al alba',
    technique: 'Curricán, spinning a comidas con stickbaits, jigging pesado (embarcación)',
    baits: 'Poppers y stickbaits grandes, jigs de 150–300 g, cebo vivo',
    minSizeNote: 'El atún rojo exige autorización específica y cupos estrictos; en recreativa suele ser captura y suelta (infórmate antes)',
    gearCats: ['carretes', 'senuelos', 'lineas'],
  },
  {
    id: 'gallo-pedro',
    name: 'Gallo de San Pedro',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_gallo_san_pedro.jpg'],
    idTraits: 'Inconfundible: cuerpo muy comprimido y alto, casi circular, con una MANCHA NEGRA REDONDA rodeada de un aro claro en el centro del flanco, y radios de la dorsal muy alargados como filamentos.',
    tagline: 'Fondos mixtos y calma, a barco',
    solunar: 24, dawnDusk: 16, night: 4, windSweet: [5, 18], windBonus: 10, windStrongAt: 32, wavePref: 'calm', pressureFall: 10,
    bestMonths: [10, 11, 12, 1, 2, 3, 4],
    seaTempC: [12, 19],
    habitat: 'Fondos mixtos de arena y roca, cerca de estructura',
    depth: '20–90 m, pegado al fondo',
    hours: 'Primeras horas, con poca corriente',
    technique: 'Pesca a fondo con vivo pequeño, jigging lento',
    baits: 'Pececillo vivo, vinilos lentos, jigs ligeros',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['anzuelos', 'lineas', 'plomos'],
  },
  {
    id: 'gallineta',
    name: 'Gallineta',
    article: 'la',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_gallineta.jpg'],
    idTraits: 'Rojo intenso, cabeza grande y espinosa con ojos muy grandes, y espinas fuertes en el opérculo. Cuerpo robusto que se afila hacia la cola. El color rojo vivo y la cabeza armada la delatan.',
    tagline: 'Profundidad y paciencia',
    solunar: 20, dawnDusk: 10, night: 6, windSweet: [4, 15], windBonus: 10, windStrongAt: 30, wavePref: 'calm', pressureFall: 10,
    bestMonths: [10, 11, 12, 1, 2, 3],
    seaTempC: [11, 17],
    habitat: 'Roca y fango profundos, cantiles y veriles',
    depth: '80–200 m desde embarcación',
    hours: 'Mañana con mar en calma y deriva lenta',
    technique: 'Pesca a fondo profundo con bajos de 2–3 anzuelos',
    baits: 'Sardina, calamar, alacha en tiras',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['plomos', 'anzuelos', 'lineas'],
  },
  {
    id: 'potas',
    name: 'Potas',
    article: 'las',
    emoji: '🦑',
    images: ['/imagenesPeces/potas.jpg'],
    idTraits: 'Cefalópodo alargado con aletas triangulares en el extremo del manto, ocupando poco más de la mitad del cuerpo. Frente al calamar, la pota es más maciza, de aletas proporcionalmente más cortas y consistencia más basta.',
    tagline: 'Noche, luz y profundidad',
    solunar: 18, dawnDusk: 10, night: 26, windSweet: [3, 15], windBonus: 10, windStrongAt: 28, wavePref: 'calm', pressureFall: 8,
    bestMonths: [10, 11, 12, 1, 2],
    seaTempC: [13, 19],
    habitat: 'Aguas profundas; de noche sube a media agua atraída por la luz',
    depth: '40–200 m, pesca nocturna a la deriva',
    hours: 'Noche cerrada, con foco o lámpara',
    technique: 'Poteras luminosas a la deriva con luz de atracción',
    baits: 'Poteras fosforescentes y de led, potera con cebo',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['senuelos', 'lineas', 'electronica'],
  },
  {
    id: 'calamares',
    name: 'Calamares',
    article: 'los',
    emoji: '🦑',
    images: ['/imagenesPeces/calamares.jpg'],
    idTraits: 'Cefalópodo de manto estrecho y alargado con aletas laterales que recorren CASI TODO el largo del manto, terminando en punta. Traslúcido con motas rojizas. Dos tentáculos más largos que el resto.',
    tagline: 'Atardeceres calmados de otoño-invierno',
    solunar: 22, dawnDusk: 22, night: 18, windSweet: [3, 14], windBonus: 12, windStrongAt: 26, wavePref: 'calm', pressureFall: 10,
    bestMonths: [9, 10, 11, 12, 1, 2],
    seaTempC: [13, 19],
    habitat: 'Arenales limpios y praderas junto a roca; puertos y bocanas',
    depth: '5–40 m, desde costa y embarcación',
    hours: 'Atardecer y primeras horas de la noche',
    technique: 'Eging con jibioneras; potera clásica fondeado',
    baits: 'Jibioneras 2.5–3.5 (naturales y llamativas), poteras con cebo',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['senuelos', 'canas', 'lineas'],
  },
  {
    id: 'galanes',
    name: 'Galán (raor)',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_galan.jpg'],
    idTraits: 'Pequeño y muy colorido, alargado y comprimido, con librea rosada-anaranjada y verdosa muy llamativa y boca pequeña de labios marcados. Los colores vivos irregulares lo distinguen de cualquier espárido.',
    tagline: 'El manjar del arenal balear',
    solunar: 22, dawnDusk: 14, night: 0, windSweet: [3, 14], windBonus: 12, windStrongAt: 26, wavePref: 'calm', pressureFall: 8,
    bestMonths: [9, 10, 11],
    seaTempC: [18, 26],
    habitat: 'Arenales limpios junto a praderas (Baleares y Levante)',
    depth: '5–40 m sobre arena, a la deriva',
    hours: 'Media mañana con sol alto y agua clara',
    technique: 'Pesca fina a fondo a la deriva con anzuelo pequeño',
    baits: 'Gamba pelada, cangrejo ermitaño, gusana',
    minSizeNote: 'Veda estricta en Baleares (apertura habitual el 1 de septiembre) y cupos: confírmalos antes de salir',
    gearCats: ['anzuelos', 'lineas', 'plomos'],
  },
  {
    id: 'pargos',
    name: 'Pargo',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_pargo.jpg'],
    idTraits: 'Espárido rosado-plateado de cuerpo alto, con las PUNTAS DE LA CAUDAL BLANQUECINAS. Sin barras verticales y sin banda dorada entre los ojos. Más rosado y de ojo mayor que la dorada.',
    tagline: 'Roca brava y cebos grandes',
    solunar: 26, dawnDusk: 20, night: 10, windSweet: [6, 20], windBonus: 12, windStrongAt: 38, wavePref: 'moderate', pressureFall: 14,
    bestMonths: [4, 5, 6, 9, 10, 11],
    seaTempC: [15, 24],
    habitat: 'Roca con arena, veriles y bajos con corriente',
    depth: '10–60 m; los grandes, pegados a la piedra',
    hours: 'Amanecer y caída de la tarde',
    technique: 'Fondo con cebos grandes, vivo, jigging lento',
    baits: 'Cangrejo, pulpo, sardina, cebo vivo',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['anzuelos', 'carretes', 'plomos'],
  },
  {
    id: 'brecas',
    name: 'Breca',
    article: 'la',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_breca.jpg'],
    idTraits: 'Espárido ROSADO uniforme, cuerpo más ESBELTO y estilizado que la dorada, hocico algo apuntado y ojo relativamente grande. SIN banda dorada entre los ojos y SIN barras verticales: eso es lo que la separa de la dorada y del sargo.',
    tagline: 'El clásico del fondo ligero',
    solunar: 22, dawnDusk: 14, night: 8, windSweet: [4, 16], windBonus: 12, windStrongAt: 30, wavePref: 'calm', pressureFall: 10,
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
    seaTempC: [14, 22],
    habitat: 'Arena y fango con roca dispersa',
    depth: '15–60 m desde embarcación fondeada o a la deriva',
    hours: 'Mañana, mejor con corriente suave',
    technique: 'Fondo ligero con bajos finos de 2–3 anzuelos',
    baits: 'Gusana, gamba, tiras de calamar',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['anzuelos', 'lineas', 'plomos'],
  },
  {
    id: 'meros',
    name: 'Mero',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_mero.jpg'],
    idTraits: 'Serránido robusto y macizo, de boca muy grande y labios gruesos, cuerpo marrón-verdoso con manchas y jaspeado irregular más claro. Aleta caudal redondeada. Cabeza ancha y perfil poderoso.',
    tagline: 'El rey de la roca — muy protegido',
    solunar: 24, dawnDusk: 16, night: 6, windSweet: [5, 20], windBonus: 10, windStrongAt: 35, wavePref: 'moderate', pressureFall: 12,
    bestMonths: [5, 6, 7, 8, 9, 10],
    seaTempC: [16, 24],
    habitat: 'Cuevas, grandes rocas y pecios',
    depth: '15–50 m, siempre pegado a su refugio',
    hours: 'Horas de luz con corriente moderada',
    technique: 'Vivo al fondo junto a la piedra, jigging',
    baits: 'Cebo vivo, pulpo, calamar entero',
    minSizeNote: 'Especie muy regulada y protegida en varias zonas: infórmate antes y valora la captura y suelta',
    gearCats: ['carretes', 'lineas', 'anzuelos'],
  },
  {
    id: 'lechas',
    name: 'Lecha (pez limón)',
    article: 'la',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_lecha_pez_limon.jpg'],
    idTraits: 'Carángido fusiforme y potente, dorso azul verdoso y flancos plateados con una BANDA AMARILLENTA longitudinal, y una franja oscura que cruza el ojo hacia la dorsal. Cola muy ahorquillada.',
    tagline: 'El torpedo de finales de verano',
    solunar: 24, dawnDusk: 22, night: 4, windSweet: [8, 28], windBonus: 12, windStrongAt: 45, wavePref: 'moderate', pressureFall: 12,
    bestMonths: [8, 9, 10, 11],
    seaTempC: [18, 26],
    habitat: 'Bajos, bocanas de puerto y estructuras; persigue alevines',
    depth: '5–50 m, ataques en superficie y media agua',
    hours: 'Alba y atardecer, con comidas visibles',
    technique: 'Cebo vivo, spinning pesado, jigging',
    baits: 'Vivo (boga, caballa), stickbaits, jigs',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['carretes', 'senuelos', 'lineas'],
  },
  {
    id: 'sepia',
    name: 'Sepia',
    article: 'la',
    emoji: '🦑',
    images: ['/imagenesPeces/sepia.jpg'],
    idTraits: 'Cefalópodo de cuerpo OVAL y ANCHO, aplanado, con una aleta estrecha que bordea todo el contorno del manto. Piel jaspeada con bandas zebradas. Mucho más ancha y plana que el calamar.',
    tagline: 'Fondo somero y agua clara en invierno-primavera',
    solunar: 20, dawnDusk: 16, night: 8, windSweet: [3, 14], windBonus: 12, windStrongAt: 26, wavePref: 'calm', pressureFall: 8,
    bestMonths: [12, 1, 2, 3, 4, 5],
    seaTempC: [12, 18],
    habitat: 'Praderas y arenales someros; entra a la costa a desovar',
    depth: '2–25 m, pegada al fondo',
    hours: 'Día y atardecer con agua clara',
    technique: 'Eging lento por el fondo con jibioneras lastradas; potera con cebo',
    baits: 'Jibioneras al fondo, cangrejo, potera cebada',
    minSizeNote: 'Cupos y medidas según la comunidad (consúltalos antes de salir)',
    gearCats: ['senuelos', 'lineas', 'anzuelos'],
  },
  {
    id: 'jurel',
    name: 'Jurel (chicharro)',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_jurel.jpg'],
    idTraits: 'Carángido plateado con una hilera de ESCUDETES ÓSEOS duros y visibles a lo largo de la línea lateral, que se arquea sobre el pectoral. Mancha oscura en el borde del opérculo. Ojo grande.',
    tagline: 'El incansable de puertos y luces',
    solunar: 20, dawnDusk: 16, night: 14, windSweet: [4, 18], windBonus: 10, windStrongAt: 32, wavePref: 'calm', pressureFall: 10,
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
    seaTempC: [14, 23],
    habitat: 'Puertos, escolleras y aguas libres cercanas; de noche, bajo las luces',
    depth: '5–60 m, en cardumen a media agua',
    hours: 'Atardecer y noche junto a luces; amanecer',
    technique: 'Sabiki, microjigging y spinning ligero',
    baits: 'Plumillas/sabiki, jigs pequeños, trocitos de sardina',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['anzuelos', 'lineas', 'senuelos'],
  },
  {
    id: 'caballa',
    name: 'Caballa',
    article: 'la',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_caballa.jpg'],
    idTraits: 'Fusiforme y pequeño, con el dorso cubierto de LÍNEAS ONDULADAS NEGRAS en zigzag sobre fondo azul verdoso, y vientre plateado sin manchas. Esas rayas onduladas del dorso son la marca definitiva; no confundir con el espetón, que es mucho más alargado y sin rayas.',
    tagline: 'La entrada de la primavera',
    solunar: 20, dawnDusk: 18, night: 6, windSweet: [5, 20], windBonus: 12, windStrongAt: 35, wavePref: 'moderate', pressureFall: 10,
    bestMonths: [3, 4, 5, 6],
    seaTempC: [13, 19],
    habitat: 'Aguas libres cercanas a la costa, espigones y bocanas',
    depth: '5–40 m, en bancos activos',
    hours: 'Mañana y última hora, con el banco cerca',
    technique: 'Sabiki/plumas, spinning ligero con jigs lanzables',
    baits: 'Plumas, jigs 10–30 g, trozo de sardina',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['anzuelos', 'senuelos', 'lineas'],
  },
  {
    id: 'palometon',
    name: 'Palometón',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_palometon.jpg'],
    idTraits: 'Carángido de cuerpo alto y comprimido, plateado con reflejos azulados, frente muy empinada y perfil casi vertical. Aletas oscuras y cola muy ahorquillada. Más alto y aplanado que la lecha.',
    tagline: 'El trofeo del spinning en desembocaduras',
    solunar: 24, dawnDusk: 24, night: 6, windSweet: [5, 22], windBonus: 12, windStrongAt: 40, wavePref: 'moderate', pressureFall: 12,
    bestMonths: [5, 6, 7, 8, 9, 10],
    seaTempC: [17, 26],
    habitat: 'Desembocaduras, playas y bocanas (Levante y Delta del Ebro)',
    depth: '0–15 m, cazando muy pegado a la orilla',
    hours: 'Alba y primeras horas; también al atardecer',
    technique: 'Spinning con needles y poppers grandes recogidos rápido',
    baits: 'Needles 14–18 cm, poppers, vivo (mújol)',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['senuelos', 'canas', 'carretes'],
  },
  {
    id: 'anjova',
    name: 'Anjova (chova)',
    article: 'la',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_anjova.jpg'],
    idTraits: 'Cuerpo robusto y algo comprimido, verdoso azulado plateado, con la BOCA GRANDE Y ARMADA de dientes cortantes bien visibles. Aleta caudal ahorquillada, dos dorsales, la primera baja.',
    tagline: 'Dientes y peleas en estuarios del sur',
    solunar: 24, dawnDusk: 20, night: 16, windSweet: [6, 24], windBonus: 12, windStrongAt: 42, wavePref: 'moderate', pressureFall: 14,
    bestMonths: [6, 7, 8, 9, 10],
    seaTempC: [18, 26],
    habitat: 'Estuarios y playas del sur (bajo Guadalquivir, bahía de Cádiz)',
    depth: '2–20 m, muy activa a media agua',
    hours: 'Atardecer y noche; amanecer',
    technique: 'Cebo (sardina) a media agua y spinning; SIEMPRE bajo de acero',
    baits: 'Sardina, vivo, paseantes y vinilos grandes',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['lineas', 'anzuelos', 'senuelos'],
  },
  {
    id: 'congrio',
    name: 'Congrio',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_congrio.jpg'],
    idTraits: 'Anguiliforme: cuerpo muy alargado y sin escamas, gris pardo, con la aleta dorsal continua que recorre casi todo el dorso y se une a la caudal. Boca grande con la mandíbula superior sobresaliendo.',
    tagline: 'La serpiente de la noche',
    solunar: 16, dawnDusk: 6, night: 26, windSweet: [3, 16], windBonus: 8, windStrongAt: 32, wavePref: 'calm', pressureFall: 8,
    bestMonths: [10, 11, 12, 1, 2, 3],
    seaTempC: [11, 18],
    habitat: 'Roca, escolleras profundas, puertos y pecios',
    depth: '15–100 m; desde costa, en espigones con fondo',
    hours: 'Noche cerrada',
    technique: 'Fondo con aparejos fuertes y cebos grandes',
    baits: 'Sardina entera, calamar, pulpo en tiras',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['plomos', 'anzuelos', 'lineas'],
  },
  {
    id: 'pulpo',
    name: 'Pulpo',
    article: 'el',
    emoji: '🐙',
    images: ['/imagenesPeces/pulpo.jpg'],
    idTraits: 'Molusco de cuerpo en saco blando sin concha y OCHO brazos con dos filas de ventosas cada uno. Piel capaz de cambiar de color y textura. Sin aletas ni tentáculos largos como el calamar.',
    tagline: 'La roca somera — normativa muy variable',
    solunar: 14, dawnDusk: 8, night: 4, windSweet: [3, 14], windBonus: 10, windStrongAt: 26, wavePref: 'calm', pressureFall: 6,
    bestMonths: [9, 10, 11, 12, 1],
    seaTempC: [13, 20],
    habitat: 'Roca somera, bolos y cuevas pequeñas',
    depth: '3–30 m, buscando huras',
    hours: 'Día con agua clara y mar en calma',
    technique: 'Pulpera trabajada a fondo, con paciencia junto a la piedra',
    baits: 'Pulperas con cangrejo o pescado sujeto',
    minSizeNote: 'Muy regulado: en varias comunidades la captura recreativa está prohibida o con peso mínimo — confírmalo antes',
    gearCats: ['senuelos', 'lineas', 'plomos'],
  },
  {
    id: 'lenguado',
    name: 'Lenguado',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_lenguado.jpg'],
    idTraits: 'Pez PLANO asimétrico, ovalado y alargado, con los DOS OJOS EN EL MISMO LADO (el derecho), cara superior parda jaspeada y cara inferior blanca. Aletas que bordean todo el contorno.',
    tagline: 'Arenas finas y noches de invierno',
    solunar: 18, dawnDusk: 10, night: 22, windSweet: [3, 16], windBonus: 10, windStrongAt: 30, wavePref: 'calm', pressureFall: 8,
    bestMonths: [10, 11, 12, 1, 2, 3],
    seaTempC: [11, 18],
    habitat: 'Arenales finos, desembocaduras y esteros',
    depth: '1–15 m, enterrado en la arena',
    hours: 'Noche, con mar tranquila',
    technique: 'Surfcasting fino a fondo con bajos largos y anzuelo pequeño',
    baits: 'Gusana (americana/coreana), tita',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['anzuelos', 'lineas', 'plomos'],
  },
  {
    id: 'herrera',
    name: 'Herrera',
    article: 'la',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_herrera.jpg'],
    idTraits: 'Espárido plateado con MUCHAS BARRAS VERTICALES OSCURAS ESTRECHAS Y FINAS a lo largo del flanco —bastantes más y más delgadas que las anchas del sargo—, hocico ALARGADO y cuerpo fusiforme. Sin banda dorada entre los ojos.',
    tagline: 'El surfcasting elegante del invierno',
    solunar: 20, dawnDusk: 14, night: 10, windSweet: [5, 18], windBonus: 12, windStrongAt: 32, wavePref: 'moderate', pressureFall: 10,
    bestMonths: [9, 10, 11, 12, 1, 2],
    seaTempC: [13, 19],
    habitat: 'Playas de arena con rompiente suave',
    depth: '1–10 m, en la misma orilla',
    hours: 'Mañana y última hora; con mar rizadita',
    technique: 'Surfcasting ligero con bajos finos de varios anzuelos',
    baits: 'Gusana americana, tita, gamba',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['anzuelos', 'lineas', 'plomos'],
  },
  {
    id: 'espeton',
    name: 'Espetón (barracuda)',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_espeton_barracuda.jpg'],
    idTraits: 'Muy ALARGADO y cilíndrico, plateado, con la mandíbula prominente llena de dientes afilados, tipo barracuda, y dos dorsales muy separadas. Cuerpo mucho más largo y delgado que cualquier caballa.',
    tagline: 'El torpedo mediterráneo de superficie',
    solunar: 22, dawnDusk: 22, night: 4, windSweet: [5, 22], windBonus: 12, windStrongAt: 38, wavePref: 'moderate', pressureFall: 10,
    bestMonths: [6, 7, 8, 9, 10, 11],
    seaTempC: [18, 26],
    habitat: 'Bocanas, escolleras y aguas someras del Mediterráneo',
    depth: '0–15 m, cazando en superficie',
    hours: 'Alba y atardecer, con comidas visibles',
    technique: 'Spinning con needles y paseantes rápidos; bajo reforzado',
    baits: 'Needles finos 12–16 cm, paseantes, vinilos',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['senuelos', 'canas', 'lineas'],
  },
  {
    id: 'bonito',
    name: 'Bonito',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_bonito.jpg'],
    idTraits: 'Túnido pequeño y esbelto con LÍNEAS OSCURAS OBLICUAS o casi longitudinales sobre el dorso azulado, y vientre plateado. Menos corpulento que el atún, con el cuerpo más afilado.',
    tagline: 'El rayado veloz de las corrientes',
    solunar: 24, dawnDusk: 22, night: 0, windSweet: [8, 25], windBonus: 12, windStrongAt: 40, wavePref: 'moderate', pressureFall: 10,
    bestMonths: [6, 7, 8, 9, 10],
    seaTempC: [18, 25],
    habitat: 'Aguas abiertas, líneas de corriente y bancos de cebo',
    depth: '0–25 m, cazando en superficie y media agua',
    hours: 'Pleno día, con comidas visibles en superficie',
    technique: 'Curricán costero, spinning a comidas con lanzados largos',
    baits: 'Plumillas, jets, jigs pequeños lanzables',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['senuelos', 'carretes', 'canas'],
  },
  {
    id: 'llampuga',
    name: 'Llampuga (dorado)',
    article: 'la',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_llampuga.jpg'],
    idTraits: 'Inconfundible: cuerpo muy comprimido y alargado con colores VERDE-AZUL Y AMARILLO ORO brillantes, y una aleta dorsal larguísima que arranca en la cabeza y recorre casi todo el dorso. Frente muy abrupta en los machos.',
    tagline: 'El color del Mediterráneo en otoño',
    solunar: 24, dawnDusk: 20, night: 0, windSweet: [6, 22], windBonus: 12, windStrongAt: 36, wavePref: 'moderate', pressureFall: 10,
    bestMonths: [8, 9, 10, 11],
    seaTempC: [20, 27],
    habitat: 'Objetos flotantes, cadufs y líneas de corriente en aguas abiertas',
    depth: '0–20 m, cazando en superficie junto a la estructura flotante',
    hours: 'Pleno día, con sol alto',
    technique: 'Curricán con plumillas junto a objetos flotantes; spinning a la vista',
    baits: 'Plumillas de colores vivos, poppers pequeños, vivo',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['senuelos', 'carretes', 'canas'],
  },
  {
    id: 'ballesta',
    name: 'Pez ballesta',
    article: 'el',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_ballesta.jpg'],
    idTraits: 'Cuerpo ovalado, muy comprimido y de piel rugosa como cuero, con una espina dorsal erectil que puede bloquear, boca pequeña de dientes fuertes y ojos altos. Aspecto acorazado, distinto a cualquier espárido.',
    tagline: 'Agua cálida y roca — cada vez más presente',
    solunar: 20, dawnDusk: 14, night: 2, windSweet: [3, 16], windBonus: 10, windStrongAt: 30, wavePref: 'calm', pressureFall: 8,
    bestMonths: [6, 7, 8, 9, 10],
    seaTempC: [20, 27],
    habitat: 'Roca, pecios y estructuras artificiales en aguas cálidas',
    depth: '5–30 m, cerca de la estructura',
    hours: 'Pleno día, con buena visibilidad',
    technique: 'Pesca a fondo fina junto a la piedra; muerde el anzuelo con mucha cautela',
    baits: 'Mejillón, gamba, cangrejo; anzuelo pequeño bien presentado',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['anzuelos', 'lineas', 'plomos'],
  },
  {
    id: 'brotola',
    name: 'Brótola',
    article: 'la',
    emoji: '🐟',
    images: ['/imagenesPeces/pez_brotola.jpg'],
    idTraits: 'Cuerpo alargado y blando, rosado pardusco, con BARBILLONES en la mandíbula y aletas dorsal y anal largas que bordean el cuerpo hasta la cola. Ojos grandes, propios de fondos profundos.',
    tagline: 'Roca profunda y horas de poca luz',
    solunar: 18, dawnDusk: 16, night: 20, windSweet: [3, 16], windBonus: 8, windStrongAt: 28, wavePref: 'calm', pressureFall: 8,
    bestMonths: [10, 11, 12, 1, 2, 3],
    seaTempC: [12, 18],
    habitat: 'Roca y cuevas profundas, cantiles y pecios',
    depth: '20–80 m, pegada al fondo y la piedra',
    hours: 'Atardecer y noche, con mar en calma',
    technique: 'Pesca a fondo con bajos cortos junto a la piedra',
    baits: 'Sardina, calamar en tiras, alacha',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['plomos', 'anzuelos', 'lineas'],
  },
]

export function getSpecies(id?: string | null): SpeciesProfile {
  return SEA_SPECIES.find((s) => s.id === id) ?? GENERAL
}

/**
 * El nombre de la especie precedido de "de", con la contracción y la
 * concordancia correctas: "del mero", "de la lubina", "de los calamares",
 * "de las potas". Para titulares del tipo `Pesca ${deSpecies(sp)}`.
 */
export function deSpecies(sp: SpeciesProfile): string {
  const n = sp.name.toLowerCase()
  switch (sp.article) {
    case 'el': return `del ${n}`
    case 'los': return `de los ${n}`
    case 'las': return `de las ${n}`
    default: return `de la ${n}`
  }
}

/**
 * El nombre con su artículo: "el mero", "la lubina", "los calamares",
 * "las potas". Para frases como `Equipo para ${elSpecies(sp)}`.
 *
 * Con `capitalizado` para cuando abre la frase: "El mero entra mejor…".
 */
export function elSpecies(sp: SpeciesProfile, capitalizado = false): string {
  const art = capitalizado ? sp.article.charAt(0).toUpperCase() + sp.article.slice(1) : sp.article
  return `${art} ${sp.name.toLowerCase()}`
}

export const MONTHS_SHORT = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']

/** Which spot `known` descriptions mention each species (shared by fichas + zone facts). */
export const SPECIES_KNOWN_TERMS: Record<string, string[]> = {
  lubina: ['lubina', 'robaliza'],
  dorada: ['dorada'],
  sargo: ['sargo'],
  corvina: ['corvina'],
  denton: ['dentón'],
  bonito: ['bonito'],
  llampuga: ['lampuga', 'llampuga'],
  atun: ['atún', 'marlin'],
  calamares: ['calamar'],
  sepia: ['sepia'],
  jurel: ['jurel', 'chicharro'],
  caballa: ['caballa'],
  palometon: ['palometón', 'palometa'],
  anjova: ['anjova', 'chova'],
  congrio: ['congrio'],
  pulpo: ['pulpo'],
  lenguado: ['lenguado'],
  herrera: ['herrera'],
  espeton: ['espetón', 'barracuda'],
  galanes: ['galán', 'raor'],
  pargos: ['pargo'],
  brecas: ['breca'],
  meros: ['mero'],
  lechas: ['lecha', 'serviola', 'pez limón', 'verderol'],
  'gallo-pedro': ['gallo'],
  gallineta: ['gallineta', 'cabracho'],
  ballesta: ['ballesta'],
  brotola: ['brótola', 'brotola'],
}
