/**
 * Sea-fishing species: scoring profiles (how each species feeds — used by the
 * hourly forecast) plus rich fact-sheet data for the /especies pages and the
 * "Qué buscar hoy" recommender. All angling guidance is orientative; legal
 * minimum sizes vary by regulation and must be checked at the official source.
 */
export interface SpeciesProfile {
  id: string
  name: string
  emoji: string
  tagline: string
  // -- hourly scoring (activity) --
  solunar: number
  dawnDusk: number
  night: number
  windSweet: [number, number]
  windBonus: number
  windStrongAt: number
  wavePref: 'rough' | 'moderate' | 'calm'
  pressureFall: number
  // -- fact sheet / recommender --
  bestMonths: number[] // 1..12
  seaTempC: [number, number] // comfortable feeding range
  habitat: string
  depth: string
  hours: string
  technique: string
  baits: string
  /** Orientative reference size — the legal one is set by regulation. */
  minSizeNote: string
  gearCats: string[]
}

export const GENERAL: SpeciesProfile = {
  id: 'general',
  name: 'General',
  emoji: '🎣',
  tagline: 'Puntuación general para cualquier especie',
  solunar: 30,
  dawnDusk: 18,
  night: 4,
  windSweet: [8, 25],
  windBonus: 14,
  windStrongAt: 45,
  wavePref: 'moderate',
  pressureFall: 14,
  bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  seaTempC: [10, 28],
  habitat: '—',
  depth: '—',
  hours: '—',
  technique: '—',
  baits: '—',
  minSizeNote: '—',
  gearCats: ['canas', 'carretes'],
}

export const SEA_SPECIES: SpeciesProfile[] = [
  {
    id: 'lubina',
    name: 'Lubina',
    emoji: '🐟',
    tagline: 'Rompiente, viento y poca luz',
    solunar: 26, dawnDusk: 22, night: 16, windSweet: [10, 35], windBonus: 16, windStrongAt: 55, wavePref: 'rough', pressureFall: 16,
    bestMonths: [9, 10, 11, 12, 1, 2, 3],
    seaTempC: [11, 20],
    habitat: 'Rompientes, espigones, desembocaduras y playas batidas',
    depth: '0–10 m, muy pegada a la orilla con mar movida',
    hours: 'Amanecer, atardecer y noche; con temporal, también de día',
    technique: 'Spinning con paseantes y jerkbaits; surfcasting nocturno',
    baits: 'Gusana, cangrejo y lanzón; señuelos de 9–14 cm',
    minSizeNote: '≈36 cm (orientativa; confirma la normativa vigente)',
    gearCats: ['senuelos', 'canas', 'carretes'],
  },
  {
    id: 'dorada',
    name: 'Dorada',
    emoji: '🐟',
    tagline: 'Aguas templadas y calmadas',
    solunar: 28, dawnDusk: 20, night: 8, windSweet: [5, 18], windBonus: 14, windStrongAt: 35, wavePref: 'calm', pressureFall: 12,
    bestMonths: [5, 6, 7, 8, 9, 10],
    seaTempC: [16, 26],
    habitat: 'Arenales, esteros y bajos rocosos con arena',
    depth: '2–15 m; entra a comer a la orilla con la subiente',
    hours: 'Primeras horas del día y cambio de marea',
    technique: 'Surfcasting a fondo con bajos finos; currican ligero',
    baits: 'Gusana americana, cangrejo ermitaño, mejillón, tita',
    minSizeNote: '≈20 cm (orientativa; confirma la normativa vigente)',
    gearCats: ['anzuelos', 'canas', 'plomos'],
  },
  {
    id: 'sargo',
    name: 'Sargo',
    emoji: '🐟',
    tagline: 'Roca con algo de marejada',
    solunar: 26, dawnDusk: 18, night: 6, windSweet: [8, 22], windBonus: 14, windStrongAt: 40, wavePref: 'moderate', pressureFall: 12,
    bestMonths: [10, 11, 12, 1, 2, 3],
    seaTempC: [12, 19],
    habitat: 'Roca batida, espigones y bocanas de puerto',
    depth: '1–8 m, en la espuma de la rompiente',
    hours: 'De día con mar movida; mejor con marea subiendo',
    technique: 'Corcheo/flotador y pesca a fondo ligera entre rocas',
    baits: 'Camarón, mejillón, erizo, gusana de roca',
    minSizeNote: '≈15 cm (orientativa; confirma la normativa vigente)',
    gearCats: ['anzuelos', 'lineas', 'canas'],
  },
  {
    id: 'corvina',
    name: 'Corvina',
    emoji: '🐟',
    tagline: 'Noche y agua removida',
    solunar: 26, dawnDusk: 20, night: 22, windSweet: [8, 28], windBonus: 14, windStrongAt: 48, wavePref: 'rough', pressureFall: 14,
    bestMonths: [5, 6, 7, 8, 9],
    seaTempC: [18, 26],
    habitat: 'Desembocaduras, esteros y playas profundas',
    depth: '2–12 m, cazando en agua turbia',
    hours: 'Noche cerrada, especialmente sin luna',
    technique: 'Surfcasting nocturno; spinning con vinilos grandes',
    baits: 'Sardina, cangrejo, vinilos XL y paseantes lentos',
    minSizeNote: '≈45 cm (orientativa; confirma la normativa vigente)',
    gearCats: ['canas', 'senuelos', 'plomos'],
  },
  {
    id: 'denton',
    name: 'Dentón',
    emoji: '🐟',
    tagline: 'Agua clara y corriente, a barco',
    solunar: 30, dawnDusk: 22, night: 2, windSweet: [5, 20], windBonus: 12, windStrongAt: 35, wavePref: 'calm', pressureFall: 12,
    bestMonths: [4, 5, 6, 9, 10, 11],
    seaTempC: [15, 24],
    habitat: 'Bajos rocosos, caídas y veriles desde embarcación',
    depth: '10–50 m sobre piedra',
    hours: 'Amanecer y horas de corriente',
    technique: 'Curricán con vivo, jigging medio-pesado',
    baits: 'Calamar y caballa viva; jigs de 100–200 g',
    minSizeNote: '≈35 cm (orientativa; confirma la normativa vigente)',
    gearCats: ['senuelos', 'carretes', 'lineas'],
  },
  {
    id: 'atun',
    name: 'Atún',
    emoji: '🐟',
    tagline: 'El gigante: corrientes, comidas y barco',
    solunar: 22, dawnDusk: 20, night: 0, windSweet: [8, 25], windBonus: 12, windStrongAt: 40, wavePref: 'moderate', pressureFall: 10,
    bestMonths: [5, 6, 7, 8, 9, 10],
    seaTempC: [18, 28],
    habitat: 'Aguas abiertas, líneas de corriente y zonas de cebo',
    depth: '0–60 m, cazando en superficie o a media agua',
    hours: 'Pleno día; comidas explosivas al alba',
    technique: 'Curricán, spinning a comidas con stickbaits, jigging pesado (embarcación)',
    baits: 'Poppers y stickbaits grandes, jigs de 150–300 g, cebo vivo',
    minSizeNote: 'El atún rojo exige autorización específica y cupos estrictos; en recreativa suele ser captura y suelta (infórmate antes)',
    gearCats: ['carretes', 'senuelos', 'lineas'],
  },
  {
    id: 'gallo-pedro',
    name: 'Gallo de San Pedro',
    emoji: '🐟',
    tagline: 'Fondos mixtos y calma, a barco',
    solunar: 24, dawnDusk: 16, night: 4, windSweet: [5, 18], windBonus: 10, windStrongAt: 32, wavePref: 'calm', pressureFall: 10,
    bestMonths: [10, 11, 12, 1, 2, 3, 4],
    seaTempC: [12, 19],
    habitat: 'Fondos mixtos de arena y roca, cerca de estructura',
    depth: '20–90 m, pegado al fondo',
    hours: 'Primeras horas, con poca corriente',
    technique: 'Pesca a fondo con vivo pequeño, jigging lento',
    baits: 'Pececillo vivo, vinilos lentos, jigs ligeros',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['anzuelos', 'lineas', 'plomos'],
  },
  {
    id: 'gallineta',
    name: 'Gallineta',
    emoji: '🐟',
    tagline: 'Profundidad y paciencia',
    solunar: 20, dawnDusk: 10, night: 6, windSweet: [4, 15], windBonus: 10, windStrongAt: 30, wavePref: 'calm', pressureFall: 10,
    bestMonths: [10, 11, 12, 1, 2, 3],
    seaTempC: [11, 17],
    habitat: 'Roca y fango profundos, cantiles y veriles',
    depth: '80–200 m desde embarcación',
    hours: 'Mañana con mar en calma y deriva lenta',
    technique: 'Pesca a fondo profundo con bajos de 2–3 anzuelos',
    baits: 'Sardina, calamar, alacha en tiras',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['plomos', 'anzuelos', 'lineas'],
  },
  {
    id: 'potas',
    name: 'Potas',
    emoji: '🦑',
    tagline: 'Noche, luz y profundidad',
    solunar: 18, dawnDusk: 10, night: 26, windSweet: [3, 15], windBonus: 10, windStrongAt: 28, wavePref: 'calm', pressureFall: 8,
    bestMonths: [10, 11, 12, 1, 2],
    seaTempC: [13, 19],
    habitat: 'Aguas profundas; de noche sube a media agua atraída por la luz',
    depth: '40–200 m, pesca nocturna a la deriva',
    hours: 'Noche cerrada, con foco o lámpara',
    technique: 'Poteras luminosas a la deriva con luz de atracción',
    baits: 'Poteras fosforescentes y de led, potera con cebo',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['senuelos', 'lineas', 'electronica'],
  },
  {
    id: 'calamares',
    name: 'Calamares',
    emoji: '🦑',
    tagline: 'Atardeceres calmados de otoño-invierno',
    solunar: 22, dawnDusk: 22, night: 18, windSweet: [3, 14], windBonus: 12, windStrongAt: 26, wavePref: 'calm', pressureFall: 10,
    bestMonths: [9, 10, 11, 12, 1, 2],
    seaTempC: [13, 19],
    habitat: 'Arenales limpios y praderas junto a roca; puertos y bocanas',
    depth: '5–40 m, desde costa y embarcación',
    hours: 'Atardecer y primeras horas de la noche',
    technique: 'Eging con jibioneras; potera clásica fondeado',
    baits: 'Jibioneras 2.5–3.5 (naturales y llamativas), poteras con cebo',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['senuelos', 'canas', 'lineas'],
  },
  {
    id: 'galanes',
    name: 'Galán (raor)',
    emoji: '🐟',
    tagline: 'El manjar del arenal balear',
    solunar: 22, dawnDusk: 14, night: 0, windSweet: [3, 14], windBonus: 12, windStrongAt: 26, wavePref: 'calm', pressureFall: 8,
    bestMonths: [9, 10, 11],
    seaTempC: [18, 26],
    habitat: 'Arenales limpios junto a praderas (Baleares y Levante)',
    depth: '5–40 m sobre arena, a la deriva',
    hours: 'Media mañana con sol alto y agua clara',
    technique: 'Pesca fina a fondo a la deriva con anzuelo pequeño',
    baits: 'Gamba pelada, cangrejo ermitaño, gusana',
    minSizeNote: 'Veda estricta en Baleares (apertura habitual el 1 de septiembre) y cupos: confírmalos antes de salir',
    gearCats: ['anzuelos', 'lineas', 'plomos'],
  },
  {
    id: 'pargos',
    name: 'Pargo',
    emoji: '🐟',
    tagline: 'Roca brava y cebos grandes',
    solunar: 26, dawnDusk: 20, night: 10, windSweet: [6, 20], windBonus: 12, windStrongAt: 38, wavePref: 'moderate', pressureFall: 14,
    bestMonths: [4, 5, 6, 9, 10, 11],
    seaTempC: [15, 24],
    habitat: 'Roca con arena, veriles y bajos con corriente',
    depth: '10–60 m; los grandes, pegados a la piedra',
    hours: 'Amanecer y caída de la tarde',
    technique: 'Fondo con cebos grandes, vivo, jigging lento',
    baits: 'Cangrejo, pulpo, sardina, cebo vivo',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['anzuelos', 'carretes', 'plomos'],
  },
  {
    id: 'brecas',
    name: 'Breca',
    emoji: '🐟',
    tagline: 'El clásico del fondo ligero',
    solunar: 22, dawnDusk: 14, night: 8, windSweet: [4, 16], windBonus: 12, windStrongAt: 30, wavePref: 'calm', pressureFall: 10,
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
    seaTempC: [14, 22],
    habitat: 'Arena y fango con roca dispersa',
    depth: '15–60 m desde embarcación fondeada o a la deriva',
    hours: 'Mañana, mejor con corriente suave',
    technique: 'Fondo ligero con bajos finos de 2–3 anzuelos',
    baits: 'Gusana, gamba, tiras de calamar',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['anzuelos', 'lineas', 'plomos'],
  },
  {
    id: 'meros',
    name: 'Mero',
    emoji: '🐟',
    tagline: 'El rey de la roca — muy protegido',
    solunar: 24, dawnDusk: 16, night: 6, windSweet: [5, 20], windBonus: 10, windStrongAt: 35, wavePref: 'moderate', pressureFall: 12,
    bestMonths: [5, 6, 7, 8, 9, 10],
    seaTempC: [16, 24],
    habitat: 'Cuevas, grandes rocas y pecios',
    depth: '15–50 m, siempre pegado a su refugio',
    hours: 'Horas de luz con corriente moderada',
    technique: 'Vivo al fondo junto a la piedra, jigging',
    baits: 'Cebo vivo, pulpo, calamar entero',
    minSizeNote: 'Especie muy regulada y protegida en varias zonas: infórmate antes y valora la captura y suelta',
    gearCats: ['carretes', 'lineas', 'anzuelos'],
  },
  {
    id: 'lechas',
    name: 'Lecha (pez limón)',
    emoji: '🐟',
    tagline: 'El torpedo de finales de verano',
    solunar: 24, dawnDusk: 22, night: 4, windSweet: [8, 28], windBonus: 12, windStrongAt: 45, wavePref: 'moderate', pressureFall: 12,
    bestMonths: [8, 9, 10, 11],
    seaTempC: [18, 26],
    habitat: 'Bajos, bocanas de puerto y estructuras; persigue alevines',
    depth: '5–50 m, ataques en superficie y media agua',
    hours: 'Alba y atardecer, con comidas visibles',
    technique: 'Cebo vivo, spinning pesado, jigging',
    baits: 'Vivo (boga, caballa), stickbaits, jigs',
    minSizeNote: 'Según la normativa de la zona (consúltala antes de salir)',
    gearCats: ['carretes', 'senuelos', 'lineas'],
  },
  {
    id: 'pelagicos',
    name: 'Bonito / Lampuga',
    emoji: '🐟',
    tagline: 'Pelágicos: día y corriente, a barco',
    solunar: 24, dawnDusk: 22, night: 0, windSweet: [8, 25], windBonus: 12, windStrongAt: 40, wavePref: 'moderate', pressureFall: 10,
    bestMonths: [6, 7, 8, 9, 10],
    seaTempC: [19, 27],
    habitat: 'Aguas abiertas, líneas de corriente y objetos flotantes',
    depth: '0–30 m, cazando en superficie',
    hours: 'Pleno día, con comidas visibles en superficie',
    technique: 'Curricán costero, spinning a comidas con lanzados largos',
    baits: 'Plumillas, jets, poppers y jigs lanzables',
    minSizeNote: 'Según especie (orientativa; confirma la normativa vigente)',
    gearCats: ['senuelos', 'carretes', 'canas'],
  },
]

export function getSpecies(id?: string | null): SpeciesProfile {
  return SEA_SPECIES.find((s) => s.id === id) ?? GENERAL
}

export const MONTHS_SHORT = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
