import type { SpeciesProfile } from '@/lib/fishing-species'

/**
 * Especies de AGUA DULCE. Separadas de `SEA_SPECIES` a propósito.
 *
 * Comparten el tipo, así que la ficha, el calendario de meses y el detector de
 * fotos funcionan igual. Pero no comparten lista, y la razón es que media
 * aplicación da por hecho que una especie vive en el mar: la malla
 * `/pesca/[especie]/[zona]` cruza especies con 187 localidades COSTERAS, y
 * `/mejores-horas` calcula mareas de puerto. Un lucio en «pescar lucio en
 * Chipiona con marea alta» sería una página absurda, y son 187 por especie.
 *
 * Por eso van aparte y con sección propia en `/rio`: entran donde tienen sentido
 * y no donde no.
 *
 * DOS DIFERENCIAS DE FONDO con el mar, que cambian los datos:
 *
 *  1. **No hay mareas.** El equivalente aquí es el nivel del embalse y la
 *     suelta de agua: un pantano que desembalsa activa la pesca igual que una
 *     corriente de marea. Como no se modela todavía, `wavePref` va en `calm`
 *     salvo en los ríos de corriente —trucha, salmón y reo—, en `moderate`.
 *  2. **La temperatura manda todavía más.** En el mar las oscilaciones son
 *     lentas; en un embalse somero el agua sube cinco grados en una semana de
 *     mayo y eso decide si el black bass está en la orilla o a doce metros.
 *
 * LEGAL, y no es un detalle menor: buena parte de las especies deportivas de
 * agua dulce en España son EXÓTICAS INVASORAS (black bass, lucio, lucioperca,
 * siluro, perca sol, alburno, pez gato). El Real Decreto 630/2013 y la Ley
 * 42/2007 prohíben su suelta, y varias comunidades obligan a sacrificar los
 * ejemplares capturados en vez de devolverlos. La norma cambia por comunidad y
 * ha ido a los tribunales más de una vez, así que cada ficha lo advierte y
 * remite a la normativa autonómica en lugar de dar una regla única.
 */

export const FRESHWATER_SPECIES: SpeciesProfile[] = [
  {
    id: 'black-bass',
    name: 'Black bass',
    article: 'el',
    emoji: '🐟',
    images: [],
    idTraits: 'Perca americana de cuerpo robusto y verdoso. Marca decisiva: BANDA OSCURA LONGITUDINAL irregular a lo largo del flanco, de la cabeza a la cola, y boca enorme cuya comisura pasa POR DETRÁS del ojo. Aleta dorsal claramente dividida en dos partes. No confundir con la perca sol, mucho más pequeña, redondeada y con manchas azuladas.',
    tagline: 'El depredador de embalse por excelencia',
    solunar: 30, dawnDusk: 24, night: 6, windSweet: [3, 15], windBonus: 12, windStrongAt: 30, wavePref: 'calm', pressureFall: 16,
    bestMonths: [4, 5, 6, 9, 10],
    seaTempC: [16, 26],
    habitat: 'Embalses y ríos remansados, con estructura: madera hundida, piedra, vegetación',
    depth: '0,5–8 m; en la orilla durante la freza y a más hondo con calor',
    hours: 'Amanecer y últimas horas de luz',
    technique: 'Spinning con vinilos, crankbait y señuelos de superficie; texas y jig entre estructura',
    baits: 'Vinilos tipo craw y shad, crankbaits, poppers, spinnerbait',
    minSizeNote: 'ESPECIE EXÓTICA INVASORA (RD 630/2013): su suelta está prohibida y varias comunidades obligan a sacrificarla. Consulta la norma de tu comunidad antes de salir.',
    gearCats: ['senuelos', 'canas', 'carretes'],
  },
  {
    id: 'lucio',
    name: 'Lucio',
    article: 'el',
    emoji: '🐟',
    images: [],
    idTraits: 'Cuerpo muy alargado y cilíndrico, verdoso con manchas claras en hileras. Marca decisiva: HOCICO ANCHO Y PLANO en forma de pico de pato, lleno de dientes, y la aleta dorsal retrasadísima, casi pegada a la caudal. No confundir con la lucioperca, que tiene el hocico puntiagudo y dos dorsales separadas.',
    tagline: 'La emboscada entre la vegetación',
    solunar: 26, dawnDusk: 22, night: 4, windSweet: [3, 16], windBonus: 12, windStrongAt: 32, wavePref: 'calm', pressureFall: 18,
    bestMonths: [1, 2, 3, 10, 11, 12],
    seaTempC: [6, 18],
    habitat: 'Embalses y tramos lentos con vegetación sumergida y cortados',
    depth: '1–6 m, pegado a la vegetación o al borde del veril',
    hours: 'Media mañana y tarde, con luz suficiente para que cace a la vista',
    technique: 'Spinning con señuelos grandes, jerkbait, vinilos y cucharillas; pesca con pez muerto',
    baits: 'Jerkbaits de 12-20 cm, vinilos grandes, cucharillas ondulantes',
    minSizeNote: 'ESPECIE EXÓTICA INVASORA (RD 630/2013): suelta prohibida y sacrificio obligatorio en varias comunidades. Usa bajo de acero o fluorocarbono grueso: corta el hilo con los dientes.',
    gearCats: ['senuelos', 'canas', 'lineas'],
  },
  {
    id: 'lucioperca',
    name: 'Lucioperca',
    article: 'la',
    emoji: '🐟',
    images: [],
    idTraits: 'Alargada y gris verdosa con barras verticales tenues. Marca decisiva: DOS ALETAS DORSALES SEPARADAS, la primera espinosa, y OJO GRANDE Y LECHOSO con brillo reflectante, adaptado a ver de noche. Colmillos visibles en la mandíbula. Hocico puntiagudo, no de pato como el lucio.',
    tagline: 'Caza cuando los demás no ven',
    solunar: 24, dawnDusk: 26, night: 22, windSweet: [4, 18], windBonus: 14, windStrongAt: 34, wavePref: 'calm', pressureFall: 14,
    bestMonths: [3, 4, 5, 9, 10, 11],
    seaTempC: [8, 20],
    habitat: 'Embalses grandes y tramos bajos del Ebro; fondos de grava y cortados',
    depth: '4–20 m; sube a la orilla al anochecer',
    hours: 'Últimas horas de luz y noche cerrada; también días muy nublados',
    technique: 'Vertical con vinilos y jigs, arrastre lento pegado al fondo, spinning nocturno',
    baits: 'Vinilos de 8-12 cm en cabeza plomada, jigs de vertical, pez muerto',
    minSizeNote: 'ESPECIE EXÓTICA INVASORA (RD 630/2013): consulta la normativa de tu comunidad, que puede exigir el sacrificio.',
    gearCats: ['senuelos', 'canas', 'plomos'],
  },
  {
    id: 'trucha-comun',
    name: 'Trucha común',
    article: 'la',
    emoji: '🐟',
    images: [],
    idTraits: 'Cuerpo fusiforme con puntos NEGROS Y ROJOS con halo claro repartidos por flancos y opérculo. Marca decisiva: aleta adiposa (pequeña y carnosa, sin radios) entre la dorsal y la cola. Coloración muy variable según el río. La arcoíris se distingue por su BANDA ROSADA lateral y por no tener puntos rojos.',
    tagline: 'Agua fría, limpia y con corriente',
    solunar: 22, dawnDusk: 26, night: 4, windSweet: [0, 12], windBonus: 8, windStrongAt: 25, wavePref: 'moderate', pressureFall: 16,
    bestMonths: [3, 4, 5, 6, 7],
    seaTempC: [6, 16],
    habitat: 'Ríos de montaña y cabeceras: tablas, rápidos y pozas con oxígeno',
    depth: '0,3–3 m; siempre donde la corriente le trae comida sin gastar energía',
    hours: 'Amanecer y las dos horas antes del anochecer; con eclosión, a cualquier hora',
    technique: 'Mosca seca y ninfa, spinning ultraligero con cucharilla y minnow',
    baits: 'Ninfas, secas de temporada, cucharillas del 0 al 2, minnows de 5-7 cm',
    minSizeNote: 'Temporada, cupos y tallas cambian por comunidad y por tramo; muchos son de captura y suelta con anzuelo sin muerte. Consulta la orden anual de tu comunidad.',
    gearCats: ['senuelos', 'canas', 'anzuelos'],
  },
  {
    id: 'trucha-arcoiris',
    name: 'Trucha arcoíris',
    article: 'la',
    emoji: '🐟',
    images: [],
    idTraits: 'Marca decisiva: BANDA ROSA O VIOLÁCEA a lo largo del flanco, de la cabeza a la cola, y puntos NEGROS pequeños repartidos también por la dorsal y la caudal. No tiene los puntos rojos con halo de la común. Cuerpo más rechoncho y coloración más uniforme.',
    tagline: 'La de repoblación, la que más pelea',
    solunar: 20, dawnDusk: 24, night: 4, windSweet: [0, 14], windBonus: 8, windStrongAt: 28, wavePref: 'calm', pressureFall: 14,
    bestMonths: [3, 4, 5, 6, 9, 10],
    seaTempC: [8, 18],
    habitat: 'Cotos intensivos, embalses y tramos repoblados',
    depth: '1–6 m; en embalse busca la capa de agua a su temperatura',
    hours: 'Todo el día en coto; amanecer y atardecer en aguas libres',
    technique: 'Spinning con cucharilla, mosca con ninfa y streamer, boya y cebo natural donde se permita',
    baits: 'Cucharillas, streamers, pasta y lombriz donde esté autorizado',
    minSizeNote: 'ESPECIE EXÓTICA (RD 630/2013), tolerada en cotos intensivos y aguas concretas. Fuera de ellos, consulta la norma de tu comunidad.',
    gearCats: ['senuelos', 'canas', 'anzuelos'],
  },
  {
    id: 'barbo',
    name: 'Barbo',
    article: 'el',
    emoji: '🐟',
    images: [],
    idTraits: 'Cuerpo alargado y dorso pardo verdoso, vientre claro. Marca decisiva: CUATRO BARBILLONES carnosos alrededor de una boca ínfera (que mira hacia abajo), y labios gruesos. El primer radio de la dorsal es una espina aserrada. No confundir con el cacho, que no tiene barbillones y es más rechoncho.',
    tagline: 'El más fuerte de nuestros ríos',
    solunar: 24, dawnDusk: 20, night: 10, windSweet: [0, 16], windBonus: 8, windStrongAt: 30, wavePref: 'calm', pressureFall: 12,
    bestMonths: [4, 5, 6, 7, 8, 9],
    seaTempC: [14, 26],
    habitat: 'Tramos medios y bajos de ríos, con fondo de grava y corriente sostenida',
    depth: '0,5–4 m; en la tabla justo detrás del rápido',
    hours: 'Media mañana en adelante, cuando el agua se calienta',
    technique: 'Fondo con plomada corredera, inglesa, y a la boloñesa en corriente',
    baits: 'Maíz, queso, lombriz, masilla y pellets donde se permita el cebado',
    minSizeNote: 'Especie autóctona. Talla y cupos varían por comunidad; algunas poblaciones (barbo comizo, de cabeza corta) están protegidas.',
    gearCats: ['anzuelos', 'canas', 'plomos'],
  },
  {
    id: 'carpa',
    name: 'Carpa',
    article: 'la',
    emoji: '🐟',
    images: [],
    idTraits: 'Cuerpo alto y macizo, dorado u oliváceo. Marca decisiva: DOS PARES DE BARBILLONES (los superiores mucho más largos) y dorsal muy larga con espina aserrada. Hay variedad royal, casi sin escamas, y de espejo, con escamas grandes y dispersas. La tenca es más pequeña, verde oscura y con ojo rojizo.',
    tagline: 'La más pescada, y la que más aguanta',
    solunar: 26, dawnDusk: 22, night: 16, windSweet: [0, 18], windBonus: 10, windStrongAt: 32, wavePref: 'calm', pressureFall: 14,
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
    seaTempC: [14, 28],
    habitat: 'Embalses, canales, lagunas y tramos lentos con fondo blando',
    depth: '1–6 m; en verano ronda la orilla al amanecer',
    hours: 'Amanecer, anochecer y noche en verano',
    technique: 'Carpfishing con pelo y plomada autoclavante, inglesa, y a la boloñesa',
    baits: 'Boilies, maíz, pellets, tigernut, masilla',
    minSizeNote: 'Muy extendida y considerada exótica en la mayoría de cuencas. Consulta la normativa de tu comunidad, sobre todo respecto a devolverla o no.',
    gearCats: ['anzuelos', 'canas', 'carretes'],
  },
  {
    id: 'siluro',
    name: 'Siluro',
    article: 'el',
    emoji: '🐟',
    images: [],
    idTraits: 'Enorme, sin escamas y de piel oscura jaspeada. Marca decisiva: SEIS BARBILLONES —dos larguísimos en la mandíbula superior y cuatro cortos en la inferior—, cabeza aplanada y anchísima, y aleta anal larguísima que recorre casi todo el vientre. Inconfundible por tamaño: supera con facilidad los dos metros.',
    tagline: 'El gigante del Ebro',
    solunar: 28, dawnDusk: 24, night: 24, windSweet: [0, 18], windBonus: 10, windStrongAt: 34, wavePref: 'calm', pressureFall: 18,
    bestMonths: [5, 6, 7, 8, 9, 10],
    seaTempC: [16, 28],
    habitat: 'Tramos bajos y embalses grandes; hoyas profundas y cortados del Ebro',
    depth: '3–25 m; sube a cazar a media agua de noche',
    hours: 'Noche cerrada y las horas de calor con agua caliente',
    technique: 'Pesca a fondo con equipo pesado, vertical con vinilos grandes, clonk desde embarcación',
    baits: 'Pez muerto, calamar, boilies grandes, vinilos de 15-25 cm',
    minSizeNote: 'ESPECIE EXÓTICA INVASORA (RD 630/2013): suelta prohibida y varias comunidades obligan a sacrificarlo. Equipo sobrado y guantes: la boca es una lija y son peces de más de 50 kg.',
    gearCats: ['canas', 'carretes', 'lineas'],
  },
  {
    id: 'boga-rio',
    name: 'Boga de río',
    article: 'la',
    emoji: '🐟',
    images: [],
    idTraits: 'Pequeña y alargada, plateada con dorso oscuro. Marca decisiva: BOCA ÍNFERA con labio inferior CORNIFICADO y recto, que usa para raspar algas de las piedras — deja marcas visibles. Sin barbillones, a diferencia del barbo. Ojo relativamente grande.',
    tagline: 'La que raspa las piedras',
    solunar: 20, dawnDusk: 18, night: 4, windSweet: [0, 14], windBonus: 6, windStrongAt: 28, wavePref: 'calm', pressureFall: 10,
    bestMonths: [4, 5, 6, 7, 8, 9],
    seaTempC: [14, 24],
    habitat: 'Tramos medios de ríos con fondo pedregoso y agua bien oxigenada',
    depth: '0,3–2 m, en corriente ligera sobre piedra',
    hours: 'Horas centrales del día',
    technique: 'Boloñesa y coup con flotador, anzuelo pequeño y bajo muy fino',
    baits: 'Masilla, pan, algas del propio río, maíz partido',
    minSizeNote: 'Autóctona y en retroceso en muchas cuencas; varias subespecies están protegidas. Consulta la normativa antes de retener ninguna.',
    gearCats: ['anzuelos', 'canas', 'lineas'],
  },
  {
    id: 'cacho',
    name: 'Cacho',
    article: 'el',
    emoji: '🐟',
    images: [],
    idTraits: 'Cuerpo robusto y cabeza ancha, plateado con reflejos bronce. Marca decisiva: escamas GRANDES y bien marcadas, boca amplia y terminal SIN barbillones, y aletas inferiores con tono anaranjado o rojizo. Más rechoncho que la boga y sin el labio córneo de ésta.',
    tagline: 'Come de todo y está en todas partes',
    solunar: 20, dawnDusk: 20, night: 6, windSweet: [0, 16], windBonus: 8, windStrongAt: 30, wavePref: 'calm', pressureFall: 12,
    bestMonths: [3, 4, 5, 6, 7, 8, 9, 10],
    seaTempC: [10, 24],
    habitat: 'Casi cualquier río: pozas, tablas y tramos con sombra de vegetación',
    depth: '0,3–3 m, muchas veces a media agua o en superficie',
    hours: 'Todo el día; muy activo con calor',
    technique: 'Spinning ultraligero, mosca seca, boloñesa con flotador',
    baits: 'Cucharilla del 0-1, saltamontes, cereza, pan, lombriz',
    minSizeNote: 'Autóctono. Sin interés gastronómico por las espinas, es un pez excelente para iniciarse y practicar captura y suelta.',
    gearCats: ['senuelos', 'canas', 'anzuelos'],
  },
  {
    id: 'perca-sol',
    name: 'Perca sol',
    article: 'la',
    emoji: '🐟',
    images: [],
    idTraits: 'Pequeña, muy alta y comprimida, con reflejos azules y naranjas. Marca decisiva: MANCHA OSCURA con borde ROJO O NARANJA en el extremo del opérculo, y líneas azuladas irradiando desde el hocico. No confundir con un black bass juvenil, que es alargado y con banda lateral.',
    tagline: 'La primera captura de casi todos',
    solunar: 16, dawnDusk: 16, night: 2, windSweet: [0, 14], windBonus: 6, windStrongAt: 26, wavePref: 'calm', pressureFall: 8,
    bestMonths: [5, 6, 7, 8, 9],
    seaTempC: [16, 28],
    habitat: 'Orillas de embalses, lagunas y remansos con vegetación',
    depth: '0,3–2 m, siempre pegada a la orilla',
    hours: 'Todo el día con sol',
    technique: 'Coup y boloñesa con flotador, microvinilos',
    baits: 'Lombriz, maíz, microvinilos de 2-4 cm',
    minSizeNote: 'ESPECIE EXÓTICA INVASORA (RD 630/2013): suelta prohibida. Compite con los alevines de las especies autóctonas.',
    gearCats: ['anzuelos', 'canas', 'lineas'],
  },
  {
    id: 'tenca',
    name: 'Tenca',
    article: 'la',
    emoji: '🐟',
    images: [],
    idTraits: 'Cuerpo macizo, verde oliva oscuro y casi negro en el dorso, con escamas diminutas hundidas en una piel muy mucosa. Marca decisiva: OJO PEQUEÑO Y ROJO ANARANJADO y un par de barbillones cortísimos en la comisura. Todas las aletas son redondeadas, sin la espina aserrada de la carpa.',
    tagline: 'El pez de las lagunas quietas',
    solunar: 22, dawnDusk: 22, night: 10, windSweet: [0, 12], windBonus: 6, windStrongAt: 26, wavePref: 'calm', pressureFall: 12,
    bestMonths: [5, 6, 7, 8, 9],
    seaTempC: [18, 28],
    habitat: 'Lagunas, charcas y canales de fondo blando y mucha vegetación',
    depth: '0,5–2,5 m, en el borde de la vegetación',
    hours: 'Amanecer y primeras horas de la tarde',
    technique: 'Coup e inglesa con flotador y cebado ligero',
    baits: 'Lombriz, maíz, masilla, casters',
    minSizeNote: 'Autóctona y con interés gastronómico y cultural en zonas como Extremadura y Salamanca. Consulta tallas y cupos de tu comunidad.',
    gearCats: ['anzuelos', 'canas', 'lineas'],
  },
  {
    id: 'anguila-rio',
    name: 'Anguila',
    article: 'la',
    emoji: '🐟',
    images: [],
    idTraits: 'Cuerpo serpentiforme y muy mucoso, sin aletas ventrales. Marca decisiva: la dorsal, la caudal y la anal forman UNA SOLA ALETA CONTINUA que rodea toda la cola. Mandíbula inferior algo más larga que la superior. Color pardo con vientre amarillento, que vira a plateado antes de migrar.',
    tagline: 'Nocturna, escurridiza y en peligro',
    solunar: 24, dawnDusk: 22, night: 28, windSweet: [0, 16], windBonus: 8, windStrongAt: 30, wavePref: 'calm', pressureFall: 16,
    bestMonths: [5, 6, 7, 8, 9, 10],
    seaTempC: [14, 26],
    habitat: 'Tramos bajos, marismas, canales y desembocaduras con fondo blando',
    depth: '0,5–5 m, siempre pegada al fondo y a los refugios',
    hours: 'Noche cerrada, sobre todo con agua turbia tras una crecida',
    technique: 'Fondo con plomada, bajos resistentes y anzuelo fuerte',
    baits: 'Lombriz, pez muerto, trozo de calamar',
    minSizeNote: 'ESPECIE EN PELIGRO CRÍTICO según la UICN, con planes de gestión europeos. Su pesca está PROHIBIDA o muy restringida en la mayoría de comunidades: comprueba la normativa antes de intentarlo y, en la duda, devuélvela.',
    gearCats: ['anzuelos', 'canas', 'plomos'],
  },
  {
    id: 'salmon',
    name: 'Salmón atlántico',
    article: 'el',
    emoji: '🐟',
    images: [],
    idTraits: 'Grande y fusiforme, plateado brillante al entrar del mar. Marca decisiva: pedúnculo caudal ESTRECHO —se puede agarrar con la mano— y caudal ligeramente ahorquillada; puntos negros en forma de X por encima de la línea lateral y casi ninguno por debajo. El reo tiene el pedúnculo grueso, la cola recta y puntos también bajo la línea lateral.',
    tagline: 'El rey de los ríos del norte',
    solunar: 26, dawnDusk: 24, night: 4, windSweet: [0, 16], windBonus: 10, windStrongAt: 30, wavePref: 'moderate', pressureFall: 18,
    bestMonths: [4, 5, 6, 7],
    seaTempC: [6, 16],
    habitat: 'Ríos salmoneros de Asturias, Cantabria, Galicia, Navarra y León',
    depth: '1–4 m, en la cola de las pozas y en las tablas de corriente',
    hours: 'Amanecer y las horas de más luz según el estado del río',
    technique: 'Mosca con streamer y tubo, cucharilla y devón donde se permita',
    baits: 'Moscas de salmón, tubos, cucharillas ondulantes',
    minSizeNote: 'PESCA MUY REGULADA: permiso específico por coto y jornada, cupos estrictos, precintado obligatorio y temporada corta. Se sortea por comunidades. Consulta la orden anual antes de nada.',
    gearCats: ['senuelos', 'canas', 'carretes'],
  },
  {
    id: 'reo',
    name: 'Reo',
    article: 'el',
    emoji: '🐟',
    images: [],
    idTraits: 'Trucha común que ha bajado al mar y vuelve: plateada y mucho más corpulenta que la de río. Marca decisiva frente al salmón: PEDÚNCULO CAUDAL GRUESO, cola recta o casi, y puntos negros TAMBIÉN POR DEBAJO de la línea lateral. La boca llega por detrás del ojo.',
    tagline: 'La trucha que volvió del mar',
    solunar: 26, dawnDusk: 28, night: 20, windSweet: [0, 16], windBonus: 10, windStrongAt: 30, wavePref: 'moderate', pressureFall: 16,
    bestMonths: [5, 6, 7, 8, 9],
    seaTempC: [10, 18],
    habitat: 'Rías y tramos bajos de los ríos del Cantábrico y Galicia',
    depth: '0,5–4 m; entra con la marea a las pozas de la ría',
    hours: 'Noche y las dos horas alrededor del amanecer',
    technique: 'Mosca nocturna, spinning con minnow y cucharilla',
    baits: 'Streamers, minnows de 7-11 cm, cucharillas',
    minSizeNote: 'Regulada como el salmón en muchos ríos: permiso, cupos y temporada específicos. Consulta la orden anual de tu comunidad.',
    gearCats: ['senuelos', 'canas', 'lineas'],
  },
]

/** Índice por id, para no recorrer la lista en cada búsqueda. */
const PORid = new Map(FRESHWATER_SPECIES.map((s) => [s.id, s]))

export function freshwaterSpecies(id: string): SpeciesProfile | undefined {
  return PORid.get(id)
}

export function isFreshwater(id: string): boolean {
  return PORid.has(id)
}
