import type { Guide } from '@/types'

// Curated starter guides. New guides can be written or AI-generated from /admin/guides.
const IMG = 'https://ae-pic-a1.aliexpress-media.com/kf'

export const GUIDE_SEED: Guide[] = [
  {
    id: 'como-elegir-tu-primera-cana-de-pescar',
    title: 'Cómo elegir tu primera caña de pescar',
    excerpt:
      'Longitud, acción, potencia y material: la guía sencilla para acertar con tu primera caña según dónde y qué quieras pescar.',
    content: [
      'Elegir la primera caña es más fácil de lo que parece si tienes claros cuatro conceptos. Vamos con ellos.',
      '',
      '**Longitud**',
      'La longitud marca el alcance del lance y el control del pez.',
      '- 1,80–2,10 m: precisión a corta distancia, ríos pequeños o kayak.',
      '- 2,40–2,70 m: la más versátil para empezar en spinning.',
      '- 3,60–4,50 m: máxima distancia desde la orilla o surfcasting.',
      '',
      '**Acción**',
      'Es dónde flexa la caña. La acción **rápida** (flexa la punta) da sensibilidad y clavadas firmes con señuelos; la **parabólica** (flexa entera) absorbe mejor los tirones de peces grandes.',
      '',
      '**Potencia**',
      'Indica el peso de señuelo/plomo recomendado (por ejemplo, 10–30 g). Elige una potencia acorde a lo que vayas a lanzar: ligera para perca y trucha, media-alta para lucio o mar.',
      '',
      '**Material**',
      'La fibra de **carbono** es ligera y sensible (ideal para notar la picada); la **fibra de vidrio** es más económica y resistente, buena para iniciarse.',
      '',
      'Consejo final: para empezar, una caña telescópica o de tramos de carbono de 2,40 m y acción rápida cubre casi todo. Mira nuestra selección de [cañas de pesca](/categories/canas).',
    ].join('\n'),
    coverImage: `${IMG}/S8c413d3dac7d48bdbe06d7e93e063d00N.jpg`,
    typeFishing: 'canas',
    seoTitle: '',
    seoDescription:
      'Cómo elegir tu primera caña de pescar: longitud, acción, potencia y material explicados sencillo para acertar según tu pesca.',
    aiOptimized: false,
    published: true,
    createdAt: '2026-07-11T09:00:00.000Z',
    updatedAt: '2026-07-11T09:00:00.000Z',
  },
  {
    id: 'guia-de-carretes-spinning-baitcasting-surfcasting',
    title: 'Guía de carretes: spinning, baitcasting y surfcasting',
    excerpt:
      'Los tres tipos de carrete más habituales, para qué sirve cada uno y en qué fijarte antes de comprar.',
    content: [
      'El carrete es la pieza que más sufre, así que merece la pena entender los tipos y elegir bien.',
      '',
      '**Carrete de spinning (frontal)**',
      'El más versátil y fácil de usar. La bobina es fija y el hilo sale por delante. Perfecto para empezar y para lanzar señuelos ligeros.',
      '- Tamaños 1000–2500: perca, trucha y finesse.',
      '- Tamaños 3000–4000: uso general y lucio.',
      '',
      '**Carrete de baitcasting (bobina giratoria)**',
      'Ofrece precisión y potencia, ideal para señuelos medianos y pesados. Tiene más curva de aprendizaje por las temidas “pelucas”: empieza con los frenos altos y aflójalos poco a poco.',
      '',
      '**Carrete de surfcasting**',
      'Grande (7000–10000), pensado para lances largos desde playa y resistente a la corrosión salina. Busca bobina cónica y buen sellado.',
      '',
      '**En qué fijarte**',
      '- Rodamientos y suavidad de recogida.',
      '- Potencia de freno (drag) suficiente para tu especie objetivo.',
      '- Materiales anticorrosión si pescas en mar.',
      '',
      'Compara modelos reales en la sección de [carretes](/categories/carretes).',
    ].join('\n'),
    coverImage: `${IMG}/S16d271cca6ea490baf57e45474420a26a.jpg`,
    typeFishing: 'carretes',
    seoTitle: '',
    seoDescription:
      'Guía de carretes de pesca: diferencias entre spinning, baitcasting y surfcasting y en qué fijarte antes de comprar.',
    aiOptimized: false,
    published: true,
    createdAt: '2026-07-09T09:00:00.000Z',
    updatedAt: '2026-07-09T09:00:00.000Z',
  },
  {
    id: 'mejores-senuelos-para-depredadores',
    title: 'Los mejores señuelos para depredadores y cómo usarlos',
    excerpt:
      'Vinilos, minnows, cucharillas y jigs: qué señuelo usar según el momento, la profundidad y la especie.',
    content: [
      'No existe el señuelo perfecto, sino el adecuado para cada situación. Estos son los imprescindibles.',
      '',
      '**Vinilos (soft baits)**',
      'Muy eficaces y económicos. Montados en cabeza plomada rastrean el fondo; con anzuelo tipo Texas son casi anti-enganche entre estructura.',
      '',
      '**Minnows y crankbaits (señuelos duros)**',
      'Imitan peces. Los minnows trabajan bien a media agua; los crankbaits de babero grande bajan más profundo y “baten” mucha agua rápido.',
      '',
      '**Cucharillas y jigs**',
      'La cucharilla giratoria es infalible para perca y trucha. Los jigs, muy pesados, permiten pescar a gran distancia o en vertical en zonas profundas.',
      '',
      '**Cuándo usar cada uno**',
      '- Amanecer y atardecer: señuelos de superficie y colores naturales.',
      '- Aguas claras: vinilos discretos y minnows realistas.',
      '- Aguas turbias: colores llamativos y vibración (crankbaits, spinnerbaits).',
      '',
      'Lleva variedad y cambia si en 15 minutos no hay actividad. Encuentra kits y modelos en [señuelos](/categories/senuelos).',
    ].join('\n'),
    coverImage: `${IMG}/Sf31b5d1820634625b622c48264d66061n.jpg`,
    typeFishing: 'senuelos',
    seoTitle: '',
    seoDescription:
      'Los mejores señuelos para depredadores: vinilos, minnows, cucharillas y jigs, y cuándo usar cada uno según la situación.',
    aiOptimized: false,
    published: true,
    createdAt: '2026-07-07T09:00:00.000Z',
    updatedAt: '2026-07-07T09:00:00.000Z',
  },
]
