import climateData from '@/content/zone-climate.json'

/**
 * Real per-zone climatology (ERA5 archive, 5 full years) generated by
 * scripts/gen-zone-climate.ts and committed as static content. Answers the
 * trip-planning question the forecast can't: "what is SEPTEMBER usually like
 * on this coast?".
 */
export interface MonthClimate {
  /** Mean daily-max wind for the month, km/h. */
  w: number
  /** % of days in the month with daily-max wind ≤ 20 km/h ("fishable"). */
  ok: number
}

const data = climateData as { generated: string; years: string; zones: Record<string, MonthClimate[]> }

export const CLIMATE_YEARS = data.years

/** Twelve months (index 0 = January) or null if the zone wasn't generated. */
export function getZoneClimate(slug: string): MonthClimate[] | null {
  const months = data.zones[slug]
  return months && months.length === 12 ? months : null
}
