#!/usr/bin/env python3
"""
Generate lib/spain-map.ts from es-atlas' autonomous_regions TopoJSON
(data © Instituto Geográfico Nacional, via the es-atlas npm package).

Decodes the topology, projects every comunidad to our fixed SVG frame
(equirectangular, aspect-corrected; Canarias in the traditional inset),
simplifies with Ramer-Douglas-Peucker in pixel space and emits static
path strings plus the exact projection constants the React map uses for
the fishing-spot dots — same math, guaranteed alignment.

Usage: python3 scripts/gen-spain-map.py <es-atlas-json> > lib/spain-map.ts
"""
import json, math, sys

SRC = sys.argv[1]
d = json.load(open(SRC))
t = d["transform"]; sx, sy = t["scale"]; tx, ty = t["translate"]

# ---- frames (keep in sync with the emitted constants) ----------------------
W, H = 700, 560
PEN = dict(lonMin=-9.85, latMax=44.05, kx=60 * math.cos(math.radians(40.0)), ky=60.0, ox=10, oy=8)
CAN = dict(lonMin=-18.35, latMax=29.5, kx=38 * math.cos(math.radians(28.5)), ky=38.0, ox=506, oy=462)
CAN_BOX = dict(x=498, y=440, w=194, h=112)

NAME_MAP = {
    "Andalucía": ("Andalucía", True),
    "Principado de Asturias": ("Asturias", True),
    "Illes Balears": ("Baleares", True),
    "Canarias": ("Canarias", True),
    "Cantabria": ("Cantabria", True),
    "Cataluña/Catalunya": ("Cataluña", True),
    "Comunitat Valenciana": ("Comunidad Valenciana", True),
    "Galicia": ("Galicia", True),
    "País Vasco/Euskadi": ("País Vasco", True),
    "Región de Murcia": ("Murcia", True),
    "Ciudad Autónoma de Ceuta": ("Ceuta", True),
    "Ciudad Autónoma de Melilla": ("Melilla", True),
    "Aragón": ("Aragón", False),
    "Castilla y León": ("Castilla y León", False),
    "Castilla-La Mancha": ("Castilla-La Mancha", False),
    "Extremadura": ("Extremadura", False),
    "Comunidad de Madrid": ("Madrid", False),
    "Comunidad Foral de Navarra": ("Navarra", False),
    "La Rioja": ("La Rioja", False),
}

def decode_arc(idx):
    arc = d["arcs"][idx]
    out, x, y = [], 0, 0
    for dx, dy in arc:
        x += dx; y += dy
        out.append((x * sx + tx, y * sy + ty))
    return out

def ring_coords(arc_indices):
    pts = []
    for i in arc_indices:
        a = decode_arc(i if i >= 0 else ~i)
        if i < 0:
            a = a[::-1]
        if pts and a and pts[-1] == a[0]:
            a = a[1:]
        pts.extend(a)
    return pts

def project(lon, lat, canary):
    f = CAN if canary else PEN
    return (f["ox"] + (lon - f["lonMin"]) * f["kx"], f["oy"] + (f["latMax"] - lat) * f["ky"])

def rdp(points, eps):
    if len(points) < 3:
        return points
    def perp(p, a, b):
        ax, ay = a; bx, by = b; px, py = p
        dx, dy = bx - ax, by - ay
        n = math.hypot(dx, dy)
        if n == 0:
            return math.hypot(px - ax, py - ay)
        return abs(dy * px - dx * py + bx * ay - by * ax) / n
    dmax, idx = 0.0, 0
    for i in range(1, len(points) - 1):
        dd = perp(points[i], points[0], points[-1])
        if dd > dmax:
            dmax, idx = dd, i
    if dmax > eps:
        left = rdp(points[: idx + 1], eps)
        right = rdp(points[idx:], eps)
        return left[:-1] + right
    return [points[0], points[-1]]

def poly_paths(geom, canary):
    polys = geom["arcs"] if geom["type"] == "MultiPolygon" else [geom["arcs"]]
    parts = []
    for poly in polys:
        for ring in poly:
            pts = [project(lon, lat, canary) for lon, lat in ring_coords(ring)]
            pts = rdp(pts, 0.75)
            if len(pts) < 4:
                continue
            path = "M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in pts) + "Z"
            parts.append(path)
    return "".join(parts)

regions = []
for g in d["objects"]["autonomous_regions"]["geometries"]:
    raw = g.get("properties", {}).get("name", "")
    if raw not in NAME_MAP:
        continue  # Gibraltar etc.
    name, coastal = NAME_MAP[raw]
    canary = name == "Canarias"
    path = poly_paths(g, canary)
    regions.append((name, coastal, canary, path))

sys.stdout.write("// AUTO-GENERATED by scripts/gen-spain-map.py — do not edit by hand.\n")
sys.stdout.write("// Outline data © Instituto Geográfico Nacional (via es-atlas), simplified.\n\n")
sys.stdout.write(f"export const MAP_W = {W}\nexport const MAP_H = {H}\n\n")
sys.stdout.write("/** Linear frames used by BOTH the outline paths and the spot dots. */\n")
sys.stdout.write(f"export const PENINSULA_FRAME = {json.dumps(PEN)}\n")
sys.stdout.write(f"export const CANARY_FRAME = {json.dumps(CAN)}\n")
sys.stdout.write(f"export const CANARY_BOX = {json.dumps(CAN_BOX)}\n\n")
sys.stdout.write("export interface RegionShape { name: string; coastal: boolean; canary: boolean; path: string }\n\n")
sys.stdout.write("export const SPAIN_REGIONS: RegionShape[] = [\n")
for name, coastal, canary, path in regions:
    sys.stdout.write(f"  {{ name: {json.dumps(name, ensure_ascii=False)}, coastal: {str(coastal).lower()}, canary: {str(canary).lower()}, path: {json.dumps(path)} }},\n")
sys.stdout.write("]\n")
