#!/usr/bin/env python3
"""
Map every fishing spot to its nearest ACTIVE AEMET observation station (one
that currently reports wind), from a fresh /observacion/convencional/todas
dump. Prefers low-altitude stations (a mountain-top anemometer 15 km inland is
worse than a harbour one 20 km away). Emits lib/aemet-stations.ts.

Usage: python3 scripts/gen-aemet-stations.py <obs.json> > lib/aemet-stations.ts
"""
import json, math, re, sys

raw = open(sys.argv[1], 'rb').read()
try:
    obs = json.loads(raw.decode('utf-8'))
except Exception:
    obs = json.loads(raw.decode('latin-1'))

stations = {}
for r in obs:
    if r.get('vv') is None or r.get('lat') is None:
        continue
    stations[r['idema']] = {
        'idema': r['idema'], 'name': (r.get('ubi') or r['idema']).replace('?', "'"),
        'lat': float(r['lat']), 'lon': float(r['lon']), 'alt': float(r.get('alt') or 0),
    }
stations = list(stations.values())

spots = []
src = open('lib/fishing-spots.ts', encoding='utf-8').read()
for m in re.finditer(r"slug: '([^']+)'.*?lat: ([\-0-9.]+), lon: ([\-0-9.]+)", src):
    spots.append((m.group(1), float(m.group(2)), float(m.group(3))))

def dist_km(a_lat, a_lon, b_lat, b_lon):
    dlat = (b_lat - a_lat) * 111.32
    dlon = (b_lon - a_lon) * 111.32 * math.cos(math.radians((a_lat + b_lat) / 2))
    return math.hypot(dlat, dlon)

out = {}
for slug, lat, lon in spots:
    best, best_score = None, 1e9
    for st in stations:
        d = dist_km(lat, lon, st['lat'], st['lon'])
        if d > 60:
            continue
        score = d + st['alt'] / 60.0  # 60 m altitude ≈ 1 km distance penalty
        if score < best_score:
            best, best_score = st, score
    if best:
        out[slug] = {'idema': best['idema'], 'name': best['name'], 'km': round(dist_km(lat, lon, best['lat'], best['lon']), 1)}

sys.stdout.write('// AUTO-GENERATED by scripts/gen-aemet-stations.py — do not edit by hand.\n')
sys.stdout.write('// Nearest ACTIVE AEMET wind-observation station per fishing spot.\n\n')
sys.stdout.write('export interface AemetStationRef { idema: string; name: string; km: number }\n\n')
sys.stdout.write('export const AEMET_STATIONS: Record<string, AemetStationRef> = {\n')
for slug, v in out.items():
    sys.stdout.write(f"  '{slug}': {{ idema: {json.dumps(v['idema'])}, name: {json.dumps(v['name'], ensure_ascii=False)}, km: {v['km']} }},\n")
sys.stdout.write('}\n')
print(f"[gen] {len(out)}/{len(spots)} zonas con estación (<60 km)", file=sys.stderr)
